### ISSUE TITLE
Doesn't work with ion-input

### ISSUE THREAD

**Issue by lhpaul** [BioPhoton/angular-formatter-parser#1]
Hello,

Im trying to make your plugin work <ion-input> but Im receiving the error "You can applied the "formatterParser" directive only on inputs or elements containing inputs"

I found out that the reason for this is because getInputElementRef() is being called to soon. The solution that I found for this is changing, in the line 63 of formatter-parser.directive.ts, ngOnInit() for   ngAfterViewInit().

**Comment by BioPhoton** [comment]
Hi @lhpaul could you please be so kind and create a PR with this changes? 
Its just one line so i guess it should be easy. 

THX for your help and the time you spent on this issue.

best Michael

**Comment by BioPhoton** [comment]
hi @lhpaul 

I have one quesion: 

I merged and reviewed you PR. There is one thing that i dont underatand.
The following code will assign the inputElement in ngOnInit only if Ionic is not present. And will do it another time in ngOnAfterViewInit. Why do you think it is a good idea to do it twice? I did not tested it in ionic so i ask stupid questions. :-p

```
 ngOnInit(): void {
    if (typeof Ionic === 'undefined') {
      this.inputElement = this.getInputElementRef();
      this.updateFormatterAndParser();
    }
  }

  ngAfterViewInit(): void {
       this.inputElement = this.getInputElementRef();
      this.updateFormatterAndParser();
  }
```

Wouldn't it be more reasonable if you do it in OnInit if no ionic is here and in AfterViewInit if Ionic is present??


```
 ngOnInit(): void {
    if (typeof Ionic === 'undefined') {
      this.inputElement = this.getInputElementRef();
      this.updateFormatterAndParser();
    }
  }

  ngAfterViewInit(): void {
    if (typeof Ionic !== 'undefined') {
      this.inputElement = this.getInputElementRef();
      this.updateFormatterAndParser();
    }
  }
```

Best 
Michael

**Comment by lhpaul** [comment]
ngAfterViewInit wasn't being called when testing the demo (it didn't work at all) so I figured out that it only works in ionic.

**Comment by BioPhoton** [comment]
Hi. ngAferViewInit works if it is defined as all lifecycle hooks gets triggered.
I made a screenshot for you.
<img width="842" alt="ngafterviewinit_works_if_defined" src="https://user-images.githubusercontent.com/10064416/28648569-00e4c17a-726f-11e7-9c3e-1a8edf54e4de.PNG">

**Comment by BioPhoton** [comment]
Ok, i guess i have a solution. At least it throws no errors. 
Take a look at this: https://github.com/BioPhoton/angular-formatter-parser/commit/82f683c42d1fb68c85fa12c76a7c2440dee5d86b

inputElement is assigned in ngAfterViewInit as in your PR and an additional check for setting the inputElement.value prop.

What do you say?

**Comment by lhpaul** [comment]
Sorry for the late response! I was on vacations...

It looks good to me!

Great work!

**Comment by BioPhoton** [comment]
I setup an ionic blank app and tested the lib. Unfortunately some wrong output. Therefor i will reopen the issue.
Have to implement testing for ionic usage. 

Help is welcome!

**Comment by cmolina** [comment]
Can you share the ionic app?

**Comment by BioPhoton** [comment]
Also a plunker is needed.

**Comment by BioPhoton** [comment]
@camolin3 Yes for sure! 
Just give me a second...

**Comment by BioPhoton** [comment]
Here you go @camolin3 => [examples/ionic3](https://github.com/BioPhoton/angular-formatter-parser/tree/master/examples/ionic3)

**Comment by BioPhoton** [comment]
@camolin3 Any updates?

**Comment by cmolina** [comment]
Sorry, I've been busy these weeks, maybe I could see this on Monday. If you have any updates please tell us.

**Comment by BioPhoton** [comment]
Haha! Me too... 
But remembered the problem and thought you gave it a try... 

c ya!

**Comment by BioPhoton** [comment]
Ill close this until the first stabel version with cursor handling is out.
